FROM osrf/ros:melodic-desktop-full

RUN apt-get update && apt-get upgrade -y && \ 
    apt-get install -y \
    xvfb \
    #ROS
    python-catkin-tools \
    python3-pip
RUN pip3 install rospkg catkin_pkg
    
RUN mkdir -p /home/catkin_ws/src \
    && echo "source /opt/ros/melodic/setup.bash" >> ~/.bashrc \
    && echo "source /home/catkin_ws/devel/setup.bash" >> ~/.bashrc

WORKDIR /home/catkin_ws/src

# How to build
# docker build -t ubeike/ros-ci_vi_grid_map -f Dockerfile.ci .