#goal definition
uint8 vi_value_theta_num_set
uint8 vi_action_theta_num_set
---
#result definition
uint8 vi_value_theta_num_current
uint8 vi_action_theta_num_current
---
#feedback
string vi_value_theta_num_status
string vi_action_theta_num_status
uint8 vi_value_store_status