name: vi_grid_map-ci

on:
  push:
    paths-ignore:
    - '**.md'

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: TEST
        run: |
          ls
          mkdir -p ~/work/src && cp -rp ~/work/vi_grid_map ~/work/src/vi_grid_map
          cd ~/work/src/vi_grid_map/vi_grid_map
          ls
          tree
          ./run.sh